config/routes.rb
AuctionApp::Application.routes.draw do
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories
  resources :items
  resources :bids,     only: [:create, :destroy]

  root "items#index"

  match '/about',   to: 'static_pages#about', via: 'get'

  match '/signup',  to: 'users#new',          via: 'get'
  match '/signin',  to: 'sessions#new',       via: 'get'
  match '/signout', to: 'sessions#destroy',   via: 'delete'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def contact
  end

  def about
  end

  def help
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<div class="about">
<h1>What is <%= print_jbay %>?</h1>
<article class="about-article">
  <%= link_to image_tag("about_icons/buy_icon.png", alt: "Buy stuff", size: "256x256"), items_path %>
  <h2>Buy</h2>
  <p>
    Anything you can think of you can buy on JBay 
    (as long as someone else has listed it). Just go to the home page and start browsing. You can browse by category, title, or vendor.
  </p>
</article>

<article class="about-article">
  <%= link_to image_tag("about_icons/sell_icon.png", alt: "Sell stuff", size: "256x256"), new_item_path %>
  <h2>Sell</h2>
  <p>
    Have some items that are taking up too much space in your life? Try listing them on JBay and see if anybody will buy it. Nothing is off limits. Sell your animals, kidneys or anything else you can think of.
  </p>
</article>
</div>

app/views/static_pages/contact.html.erb
<h1>Contact Us</h1>
<p>If you have any questions regarding JBay, email us!</p>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<h2>FAQ</h2>
<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Answer</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>How do I sell something?</td>
      <td>You don't yet, this application is still under heavy development</td>
    </tr>
    <tr>
      <td>How long until it's ready?</td>
      <td>About a week</td>
    </tr>
  </tbody>
</table>