config/routes.rb
AuctionApp::Application.routes.draw do
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories
  resources :items
  resources :bids,     only: [:create, :destroy]

  root "items#index"

  match '/about',   to: 'static_pages#about', via: 'get'

  match '/signup',  to: 'users#new',          via: 'get'
  match '/signin',  to: 'sessions#new',       via: 'get'
  match '/signout', to: 'sessions#destroy',   via: 'delete'

end

app/models/item.rb
class Item < ActiveRecord::Base
  
  default_scope -> { order('created_at DESC') }
  belongs_to :category
  belongs_to :user
  has_many :bids, dependent: :destroy

  has_attached_file :image_preview, 
                    :styles => { :medium => "256x256#", :thumb => "180x180#" },
                    :default_url => "missing.png"
  validates_attachment_content_type :image_preview, 
  :content_type => ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']

  validates :name, presence: true, length: { maximum: 50 }
  validates :category_id, presence: true
  validates :user_id,     presence: true
  validates :finish_time, presence: true

  def self.search(name, category_id)
    if !category_id.empty?
      # search with category_id
      where("name || description LIKE ? AND category_id = ?", 
            "%#{name}%", "#{category_id}")
    else
      # there is no category_id
      where("name || description LIKE ?",
            "%#{name}%")
    end
  end

  def self.find_won_items(user)
    @won_items = []
   
    user.bids.each do |bid|
      if user.id == Bid.find_highest_bidder(bid.item) && bid.item.finish_time < Time.now
        @won_items.push(bid.item)
      end
    end
    @won_items.uniq
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item,                      only: [:show, :edit, :update, :destroy]
  before_action :set_categories,                only: [:edit, :new, :create, :index]
  before_action :set_days,                      only: [:new, :create, :edit, :update]

  before_action :auth_new_item,                 only: [:new, :create]
  before_action :auth_edit_update_destroy_item, only: [:edit, :update, :destroy]
  before_action :auth_edit_update_no_bids,      only: [:edit, :update]

  def index
    if (params[:search] && params[:category])
      # this will search the DB for the specified params
      # and return them ordered by last created first
      @items = Item.search(params[:search], params[:category]).order("created_at DESC")
    else
      @items = Item.all
    end
    # then paginate the items
    @items = @items.paginate(page: params[:page], per_page: 5)
  end

  def show
    @bid = Bid.new
    @bids = Bid.where("item_id = ?", @item.id)
    @bids = @bids.paginate(page: params[:page], per_page: 5)
  end

  def edit

  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save   #success
      redirect_to @item, notice: "Item created successfully"
    else            # failure
      render action: 'new'
    end
  end

  def update
    if @item.update(item_params)
      redirect_to @item, notice: "Item updated successully"
    else
      render action: 'edit'
    end
  end

  def destroy
    @item.destroy
    redirect_to root_path, notice: "Item deleted"
  end

  private

    def auth_new_item
      unless signed_in?
        store_location
        redirect_to signin_path, notice: "Please sign in"
      end
    end

    def auth_edit_update_destroy_item
      unless signed_in? && (@item.user_id == current_user.id || current_user.admin)
        store_location
        redirect_to signin_path, notice: "Please sign in"
      end
    end

    def set_item
      @item = Item.find(params[:id])
    end

    def auth_edit_update_no_bids
      if @item.bids.count > 0
        redirect_to @item, notice: "This item has been bid on and cannot be edited"
      end
    end

    # this method collects the category names and id's
    # for the dropdown menu in the form
    def set_categories
      @categories = Category.all.collect { |c| [c.name, c.id] }
    end

    # sets the days with datetimes for the new item form
    def set_days
      @days = []
      (1..30).each do |i|
        @days.push([(ActionController::Base.helpers.pluralize(i, 'day')),
                    (Time.now + i.days)])
      end
      @days
    end

    def item_params
      params.require(:item).permit(:name, :description, :user_id,
                                   :starting_price, :category_id, 
                                   :finish_time, :image_preview)
    end

end

app/helpers/items_helper.rb
module ItemsHelper

  def item_expired?(item)
    if item.finish_time
      item.finish_time - Time.now < 0
    end
  end

  # Function created by Shippy (https://gist.github.com/xxMShipmanxx/8732888)
  # Takes the time and calculates how long it has left before the time expires
  def time_to_natural_language(time_left)
    if time_left > 0
      time_left = time_left.round.to_i
   
      weeks = time_left / 604800
      time_left -= weeks * 604800
   
      days = time_left / 86400
      time_left -= days * 86400
     
      hours = time_left / 3600
      time_left -= hours * 3600
   
      minutes = time_left / 60
      time_left -= minutes * 60
   
      seconds = time_left
   
      weeks   = weeks.to_s
      days    = days.to_s
      hours   = hours.to_s
      minutes = minutes.to_s
      seconds = seconds.to_s
   
      if weeks.to_i > 0
        pluralize(weeks, 'week')
      elsif days.to_i > 0
        pluralize(days, 'day')
      elsif hours.to_i > 0
        pluralize(hours, 'hours') + ", " + pluralize(minutes, 'minute')
      else
        pluralize(minutes, 'minute') + ", " + pluralize(seconds, 'second')
      end

    else
      "No time"
    end
  end

  def datetime_to_natural_format(datetime)
    datetime.strftime('%e %b %Y %H:%m:%S%p')
  end

end

app/views/items/_edit_form.html.erb
<%= form_for(@item) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
        <%= f.label :name, class: "required" %><br>
        <%= f.text_field :name %>
    </div>
    <div class="field">
        <%= f.label :description %><br>
        <%= f.text_area :description %>
    </div>
    <div class="field">
        <%= f.label :starting_price, class: "required" %><br>
        <%= f.number_field :starting_price, { min: 0.99, max: 999999.99, step: 0.01 } %>
    </div>
    <div class="field">
        Category<br>
        <%= f.select(:category_id, options_for_select(@categories, selected: @item.category_id),
                     prompt: "Select a category") %>
    </div>
    <div class="field">
        Upload image<br>
        <%= f.file_field :image_preview %>
    </div>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.submit "List item" %>
<% end %>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
        <%= f.label :name, class: "required" %><br>
        <%= f.text_field :name %>
    </div>
    <div class="field">
        <%= f.label :description %><br>
        <%= f.text_area :description %>
    </div>
    <div class="field">
        <%= f.label :starting_price, class: "required" %><br>
        <%= f.number_field :starting_price, { min: 0.99, max: 999999.99, step: 0.01 } %>
    </div>
    <div class="field">
        Category<br>
        <%= f.select(:category_id, options_for_select(@categories, selected: @item.category_id),
                     prompt: "Select a category") %>
    </div>
    <div class="field">
        Auction duration<br>
        <%= f.select(:finish_time, options_for_select(@days),
                     prompt: "How many days?") %>
    </div>
    <div class="field">
        Upload image<br>
        <%= f.file_field :image_preview %>
    </div>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.submit "List item" %>
<% end %>

app/views/items/_item_details.html.erb
<article class="item-details">
  <div class="image"><%= image_tag @item.image_preview.url(:medium) %></div>
  <div class="details">
    <h1><%= @item.name %></h1>
    <h2><%= number_to_currency(find_highest_bid_for(@item)) %></h2>
    <h3><span>Seller:</span> <%= link_to @item.user.name, @item.user %></h3>
    <h4><span>Category:</span> <%= @item.category.name %></h4>
    <% if @item.finish_time > Time.now %>
      <h4><span>Finishes on:</span> <%= datetime_to_natural_format(@item.finish_time) %></h4>
    <% else %>
      <h5>Item ended</h5>
    <% end %>
    <p><%= @item.description %></p>
  </div>
</article>

app/views/items/_user_options.html.erb
<div class="user-settings">
  <p class="title">Admin Panel</p>
  <% if @item.bids.count == 0 %>
    <p><%= link_to 'Edit item', edit_item_path(@item) %></p>
  <% end %>
  <p class="delete-account"><%= link_to 'Delete item', @item, method: :delete, data: { confirm: 'Are you sure?' } %></p>
</div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'edit_form' %>

<%= link_to 'Cancel', root_path %>

app/views/items/index.html.erb
<div class="fixed-header">
  <h1>Welcome to <%= print_jbay %></h1>
  <%= render 'shared/search' %>
  <% if signed_in? %>
  <p class="sell">Got something to sell? <%= link_to 'List a new item', new_item_path %></p>
  <% end %>
</div>

<div class="item-index"></div>

<div class="item-articles">
  <%= content_tag(:p, notice, id: "notice") unless notice.nil? %>
  <%= will_paginate @items %>

  <% @items.each do |item| %>
  <article class="item-preview">
    <div class="item-thumb"><%= image_tag item.image_preview.url(:thumb) %></div>
    <div class="details">
      <h2><%= link_to item.name, item %></h2>
      <h3><%= number_to_currency(find_highest_bid_for(item)) %></h3>
      <h3><%= item.category.name %></h3>
      <h3><%= time_to_natural_language(item.finish_time - Time.now) %> remaining</h3>
    </div>
  </article>
  <% end %>

  <%= will_paginate @items %>
</div>

app/views/items/new.html.erb
<h1>New listing</h1>

<%= render 'form' %>

<%= link_to 'Cancel', root_path %>

app/views/items/show.html.erb
<%= content_tag(:p, notice, id: "notice") unless notice.nil? %>

<%= render 'item_details' %>

<aside id="item-sidebar">
  <% if signed_in? && @item.user_id == current_user.id %>
    <%= render 'user_options' %>
  <% end %>
  <% if signed_in? && current_user.id != @item.user_id && !item_expired?(@item) %>
    <%= render 'bids/form' %>
  <% end %>
  <%= render 'bids/index' %>

</aside>
<p class="clear"></p>