config/routes.rb
AuctionApp::Application.routes.draw do
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories
  resources :items
  resources :bids,     only: [:create, :destroy]

  root "items#index"

  match '/about',   to: 'static_pages#about', via: 'get'

  match '/signup',  to: 'users#new',          via: 'get'
  match '/signin',  to: 'sessions#new',       via: 'get'
  match '/signout', to: 'sessions#destroy',   via: 'delete'

end

app/views/layouts/_footer.html.erb
<footer class="group">
  <p>Joshua Newman | s2892398 </p>
  <%= link_to "Assignment 1 Documentation", "A1_doc.html", target: "_blank" %><br>
  <%= link_to "Assignment 2 Documentation", "A2_doc.html", target: "_blank" %>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav id="main-nav">
    <h1><%= link_to print_jbay,
            root_path %></h1>
    <ul>
      <li><%= link_to "Items", items_path %></li> |
      <li><%= link_to "About", about_path %></li> |
      <% if signed_in? %>
        <% if current_user.admin? %>
          <li><%= link_to "Categories", categories_path %></li> |
        <% end %>
        <li><%= link_to "Users", users_path %></li> |
        <li><%= gravatar_for(current_user) %></li>
        <li><%= link_to current_user.name, current_user %>
          <ul>
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset='utf-8'>
  <title>JBay | Buy and sell</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag params[:controller] %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="pusher"></div>
  <div class="main-body">
    <div class="container">
      <%= yield %>  
    </div>
  </div>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>